// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: ledger/v1/ledger.proto

package ledgerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LedgerService_Append_FullMethodName         = "/ledger.v1.LedgerService/Append"
	LedgerService_Read_FullMethodName           = "/ledger.v1.LedgerService/Read"
	LedgerService_Count_FullMethodName          = "/ledger.v1.LedgerService/Count"
	LedgerService_SetTags_FullMethodName        = "/ledger.v1.LedgerService/SetTags"
	LedgerService_SetAnnotations_FullMethodName = "/ledger.v1.LedgerService/SetAnnotations"
	LedgerService_Trim_FullMethodName           = "/ledger.v1.LedgerService/Trim"
	LedgerService_ListStreamIDs_FullMethodName  = "/ledger.v1.LedgerService/ListStreamIDs"
	LedgerService_Health_FullMethodName         = "/ledger.v1.LedgerService/Health"
)

// LedgerServiceClient is the client API for LedgerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LedgerService exposes the append-only log operations over gRPC.
//
// A server instance is bound to exactly one store (table / collection).
// Within that store, streams are identified by the "stream" field in each request.
type LedgerServiceClient interface {
	// Append adds entries to the named stream.
	// Entries whose DedupKey already exists in the stream are silently skipped.
	// Returns the IDs assigned to newly written entries (skipped entries are omitted).
	Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*AppendResponse, error)
	// Read returns entries from the named stream, ordered by ID.
	// An empty stream returns an empty list (not an error).
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	// Count returns the total number of entries in the named stream.
	Count(ctx context.Context, in *CountRequest, opts ...grpc.CallOption) (*CountResponse, error)
	// SetTags replaces all tags on an existing entry.
	// Returns NOT_FOUND if the entry does not exist.
	SetTags(ctx context.Context, in *SetTagsRequest, opts ...grpc.CallOption) (*SetTagsResponse, error)
	// SetAnnotations merges key-value annotations onto an existing entry.
	// Keys present in "set" are upserted; keys present in "delete" are removed.
	// Returns NOT_FOUND if the entry does not exist.
	SetAnnotations(ctx context.Context, in *SetAnnotationsRequest, opts ...grpc.CallOption) (*SetAnnotationsResponse, error)
	// Trim deletes entries whose ID is less than or equal to before_id.
	// Returns the number of entries deleted.
	Trim(ctx context.Context, in *TrimRequest, opts ...grpc.CallOption) (*TrimResponse, error)
	// ListStreamIDs returns distinct stream IDs that have at least one entry.
	// Streams that have been fully trimmed are not returned.
	// Results are ascending by stream ID and cursor-paginated via after / limit.
	ListStreamIDs(ctx context.Context, in *ListStreamIDsRequest, opts ...grpc.CallOption) (*ListStreamIDsResponse, error)
	// Health reports backend connectivity. Returns status "ok" on success,
	// or a description of the problem on failure.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type ledgerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLedgerServiceClient(cc grpc.ClientConnInterface) LedgerServiceClient {
	return &ledgerServiceClient{cc}
}

func (c *ledgerServiceClient) Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*AppendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendResponse)
	err := c.cc.Invoke(ctx, LedgerService_Append_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, LedgerService_Read_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) Count(ctx context.Context, in *CountRequest, opts ...grpc.CallOption) (*CountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountResponse)
	err := c.cc.Invoke(ctx, LedgerService_Count_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) SetTags(ctx context.Context, in *SetTagsRequest, opts ...grpc.CallOption) (*SetTagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetTagsResponse)
	err := c.cc.Invoke(ctx, LedgerService_SetTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) SetAnnotations(ctx context.Context, in *SetAnnotationsRequest, opts ...grpc.CallOption) (*SetAnnotationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetAnnotationsResponse)
	err := c.cc.Invoke(ctx, LedgerService_SetAnnotations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) Trim(ctx context.Context, in *TrimRequest, opts ...grpc.CallOption) (*TrimResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrimResponse)
	err := c.cc.Invoke(ctx, LedgerService_Trim_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) ListStreamIDs(ctx context.Context, in *ListStreamIDsRequest, opts ...grpc.CallOption) (*ListStreamIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStreamIDsResponse)
	err := c.cc.Invoke(ctx, LedgerService_ListStreamIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, LedgerService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LedgerServiceServer is the server API for LedgerService service.
// All implementations must embed UnimplementedLedgerServiceServer
// for forward compatibility.
//
// LedgerService exposes the append-only log operations over gRPC.
//
// A server instance is bound to exactly one store (table / collection).
// Within that store, streams are identified by the "stream" field in each request.
type LedgerServiceServer interface {
	// Append adds entries to the named stream.
	// Entries whose DedupKey already exists in the stream are silently skipped.
	// Returns the IDs assigned to newly written entries (skipped entries are omitted).
	Append(context.Context, *AppendRequest) (*AppendResponse, error)
	// Read returns entries from the named stream, ordered by ID.
	// An empty stream returns an empty list (not an error).
	Read(context.Context, *ReadRequest) (*ReadResponse, error)
	// Count returns the total number of entries in the named stream.
	Count(context.Context, *CountRequest) (*CountResponse, error)
	// SetTags replaces all tags on an existing entry.
	// Returns NOT_FOUND if the entry does not exist.
	SetTags(context.Context, *SetTagsRequest) (*SetTagsResponse, error)
	// SetAnnotations merges key-value annotations onto an existing entry.
	// Keys present in "set" are upserted; keys present in "delete" are removed.
	// Returns NOT_FOUND if the entry does not exist.
	SetAnnotations(context.Context, *SetAnnotationsRequest) (*SetAnnotationsResponse, error)
	// Trim deletes entries whose ID is less than or equal to before_id.
	// Returns the number of entries deleted.
	Trim(context.Context, *TrimRequest) (*TrimResponse, error)
	// ListStreamIDs returns distinct stream IDs that have at least one entry.
	// Streams that have been fully trimmed are not returned.
	// Results are ascending by stream ID and cursor-paginated via after / limit.
	ListStreamIDs(context.Context, *ListStreamIDsRequest) (*ListStreamIDsResponse, error)
	// Health reports backend connectivity. Returns status "ok" on success,
	// or a description of the problem on failure.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedLedgerServiceServer()
}

// UnimplementedLedgerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLedgerServiceServer struct{}

func (UnimplementedLedgerServiceServer) Append(context.Context, *AppendRequest) (*AppendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Append not implemented")
}
func (UnimplementedLedgerServiceServer) Read(context.Context, *ReadRequest) (*ReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedLedgerServiceServer) Count(context.Context, *CountRequest) (*CountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Count not implemented")
}
func (UnimplementedLedgerServiceServer) SetTags(context.Context, *SetTagsRequest) (*SetTagsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetTags not implemented")
}
func (UnimplementedLedgerServiceServer) SetAnnotations(context.Context, *SetAnnotationsRequest) (*SetAnnotationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetAnnotations not implemented")
}
func (UnimplementedLedgerServiceServer) Trim(context.Context, *TrimRequest) (*TrimResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Trim not implemented")
}
func (UnimplementedLedgerServiceServer) ListStreamIDs(context.Context, *ListStreamIDsRequest) (*ListStreamIDsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListStreamIDs not implemented")
}
func (UnimplementedLedgerServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedLedgerServiceServer) mustEmbedUnimplementedLedgerServiceServer() {}
func (UnimplementedLedgerServiceServer) testEmbeddedByValue()                       {}

// UnsafeLedgerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LedgerServiceServer will
// result in compilation errors.
type UnsafeLedgerServiceServer interface {
	mustEmbedUnimplementedLedgerServiceServer()
}

func RegisterLedgerServiceServer(s grpc.ServiceRegistrar, srv LedgerServiceServer) {
	// If the following call panics, it indicates UnimplementedLedgerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LedgerService_ServiceDesc, srv)
}

func _LedgerService_Append_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).Append(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_Append_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).Append(ctx, req.(*AppendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_Read_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_Count_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).Count(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_Count_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).Count(ctx, req.(*CountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_SetTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).SetTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_SetTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).SetTags(ctx, req.(*SetTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_SetAnnotations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAnnotationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).SetAnnotations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_SetAnnotations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).SetAnnotations(ctx, req.(*SetAnnotationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_Trim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrimRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).Trim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_Trim_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).Trim(ctx, req.(*TrimRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_ListStreamIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStreamIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).ListStreamIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_ListStreamIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).ListStreamIDs(ctx, req.(*ListStreamIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LedgerService_ServiceDesc is the grpc.ServiceDesc for LedgerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LedgerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ledger.v1.LedgerService",
	HandlerType: (*LedgerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Append",
			Handler:    _LedgerService_Append_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _LedgerService_Read_Handler,
		},
		{
			MethodName: "Count",
			Handler:    _LedgerService_Count_Handler,
		},
		{
			MethodName: "SetTags",
			Handler:    _LedgerService_SetTags_Handler,
		},
		{
			MethodName: "SetAnnotations",
			Handler:    _LedgerService_SetAnnotations_Handler,
		},
		{
			MethodName: "Trim",
			Handler:    _LedgerService_Trim_Handler,
		},
		{
			MethodName: "ListStreamIDs",
			Handler:    _LedgerService_ListStreamIDs_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _LedgerService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ledger/v1/ledger.proto",
}
