// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ledger/v1/ledger.proto

package ledgerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EntryInput describes a single entry to be appended.
type EntryInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// payload is the raw serialised payload bytes (JSON, protobuf, etc.).
	// The server stores it verbatim; no re-encoding is performed.
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	// order_key is an optional secondary ordering key used for filtering
	// (e.g., an aggregate ID or category string).
	OrderKey string `protobuf:"bytes,2,opt,name=order_key,json=orderKey,proto3" json:"order_key,omitempty"`
	// dedup_key enables idempotent appends. If a non-empty key already exists
	// in the stream the entry is silently skipped. Empty means no dedup.
	DedupKey string `protobuf:"bytes,3,opt,name=dedup_key,json=dedupKey,proto3" json:"dedup_key,omitempty"`
	// schema_version is stamped on the entry at write time. Defaults to 1.
	SchemaVersion int64 `protobuf:"varint,4,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	// metadata is immutable key-value data set at append time
	// (e.g., trace_id, source, tenant_id).
	Metadata map[string]string `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// tags is the initial set of mutable labels on the entry.
	Tags          []string `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntryInput) Reset() {
	*x = EntryInput{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryInput) ProtoMessage() {}

func (x *EntryInput) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryInput.ProtoReflect.Descriptor instead.
func (*EntryInput) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{0}
}

func (x *EntryInput) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EntryInput) GetOrderKey() string {
	if x != nil {
		return x.OrderKey
	}
	return ""
}

func (x *EntryInput) GetDedupKey() string {
	if x != nil {
		return x.DedupKey
	}
	return ""
}

func (x *EntryInput) GetSchemaVersion() int64 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *EntryInput) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *EntryInput) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// Entry is a stored ledger entry returned by Read.
type Entry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the store-assigned unique identifier (decimal int64 for SQL backends,
	// hex ObjectID string for MongoDB).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// stream is the stream this entry belongs to.
	Stream string `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"`
	// payload is the raw serialised payload as stored (see EntryInput.payload).
	Payload  []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	OrderKey string `protobuf:"bytes,4,opt,name=order_key,json=orderKey,proto3" json:"order_key,omitempty"`
	DedupKey string `protobuf:"bytes,5,opt,name=dedup_key,json=dedupKey,proto3" json:"dedup_key,omitempty"`
	// schema_version is the version stamped at write time.
	SchemaVersion int64 `protobuf:"varint,6,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	// metadata is the immutable key-value data set at append time.
	Metadata map[string]string `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// tags are the current mutable labels on the entry.
	Tags []string `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	// annotations are the current mutable key-value state on the entry.
	Annotations map[string]string `protobuf:"bytes,9,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// created_at is the timestamp when the entry was stored.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// updated_at is the timestamp of the last tag or annotation update,
	// absent if the entry has never been mutated.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{1}
}

func (x *Entry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Entry) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *Entry) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Entry) GetOrderKey() string {
	if x != nil {
		return x.OrderKey
	}
	return ""
}

func (x *Entry) GetDedupKey() string {
	if x != nil {
		return x.DedupKey
	}
	return ""
}

func (x *Entry) GetSchemaVersion() int64 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *Entry) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Entry) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Entry) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *Entry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Entry) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// ReadOptions configures how entries are fetched from a stream.
// All fields are optional; zero values mean "use the backend default".
type ReadOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// after is the cursor: only entries whose ID is strictly greater than this
	// value are returned. Empty string means "from the beginning".
	After string `protobuf:"bytes,1,opt,name=after,proto3" json:"after,omitempty"`
	// limit caps the number of entries returned. 0 means the backend default (100).
	Limit int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// desc returns entries newest-first (descending by ID) when true.
	Desc bool `protobuf:"varint,3,opt,name=desc,proto3" json:"desc,omitempty"`
	// order_key filters entries by their order_key field.
	OrderKey string `protobuf:"bytes,4,opt,name=order_key,json=orderKey,proto3" json:"order_key,omitempty"`
	// tag filters entries that carry this single tag.
	Tag string `protobuf:"bytes,5,opt,name=tag,proto3" json:"tag,omitempty"`
	// all_tags filters entries that carry ALL of the specified tags.
	AllTags       []string `protobuf:"bytes,6,rep,name=all_tags,json=allTags,proto3" json:"all_tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadOptions) Reset() {
	*x = ReadOptions{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadOptions) ProtoMessage() {}

func (x *ReadOptions) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadOptions.ProtoReflect.Descriptor instead.
func (*ReadOptions) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{2}
}

func (x *ReadOptions) GetAfter() string {
	if x != nil {
		return x.After
	}
	return ""
}

func (x *ReadOptions) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ReadOptions) GetDesc() bool {
	if x != nil {
		return x.Desc
	}
	return false
}

func (x *ReadOptions) GetOrderKey() string {
	if x != nil {
		return x.OrderKey
	}
	return ""
}

func (x *ReadOptions) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *ReadOptions) GetAllTags() []string {
	if x != nil {
		return x.AllTags
	}
	return nil
}

type AppendRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// stream is the stream to append to. Must not be empty.
	Stream string `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	// entries is the batch of entries to append. An empty batch is a no-op.
	Entries       []*EntryInput `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendRequest) Reset() {
	*x = AppendRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendRequest) ProtoMessage() {}

func (x *AppendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendRequest.ProtoReflect.Descriptor instead.
func (*AppendRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{3}
}

func (x *AppendRequest) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *AppendRequest) GetEntries() []*EntryInput {
	if x != nil {
		return x.Entries
	}
	return nil
}

type AppendResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ids are the store-assigned IDs for entries that were successfully written.
	// Deduplicated (skipped) entries are absent from this list.
	// The order matches the order of non-skipped entries in the request.
	Ids           []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendResponse) Reset() {
	*x = AppendResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendResponse) ProtoMessage() {}

func (x *AppendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendResponse.ProtoReflect.Descriptor instead.
func (*AppendResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{4}
}

func (x *AppendResponse) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type ReadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// stream is the stream to read from. Must not be empty.
	Stream string `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	// options configures filtering, ordering, and pagination.
	Options       *ReadOptions `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{5}
}

func (x *ReadRequest) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *ReadRequest) GetOptions() *ReadOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type ReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*Entry               `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{6}
}

func (x *ReadResponse) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type CountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        string                 `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountRequest) Reset() {
	*x = CountRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountRequest) ProtoMessage() {}

func (x *CountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountRequest.ProtoReflect.Descriptor instead.
func (*CountRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{7}
}

func (x *CountRequest) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

type CountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountResponse) Reset() {
	*x = CountResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountResponse) ProtoMessage() {}

func (x *CountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountResponse.ProtoReflect.Descriptor instead.
func (*CountResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{8}
}

func (x *CountResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type SetTagsRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Stream string                 `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	// id is the entry ID as returned by Append or Read.
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// tags replaces the entire tag list on the entry.
	Tags          []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTagsRequest) Reset() {
	*x = SetTagsRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTagsRequest) ProtoMessage() {}

func (x *SetTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTagsRequest.ProtoReflect.Descriptor instead.
func (*SetTagsRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{9}
}

func (x *SetTagsRequest) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *SetTagsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SetTagsRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type SetTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTagsResponse) Reset() {
	*x = SetTagsResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTagsResponse) ProtoMessage() {}

func (x *SetTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTagsResponse.ProtoReflect.Descriptor instead.
func (*SetTagsResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{10}
}

type SetAnnotationsRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Stream string                 `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	// id is the entry ID as returned by Append or Read.
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// set contains key-value pairs to upsert onto the entry's annotations.
	Set map[string]string `protobuf:"bytes,3,rep,name=set,proto3" json:"set,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// delete lists annotation keys to remove from the entry.
	Delete        []string `protobuf:"bytes,4,rep,name=delete,proto3" json:"delete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAnnotationsRequest) Reset() {
	*x = SetAnnotationsRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAnnotationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAnnotationsRequest) ProtoMessage() {}

func (x *SetAnnotationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAnnotationsRequest.ProtoReflect.Descriptor instead.
func (*SetAnnotationsRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{11}
}

func (x *SetAnnotationsRequest) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *SetAnnotationsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SetAnnotationsRequest) GetSet() map[string]string {
	if x != nil {
		return x.Set
	}
	return nil
}

func (x *SetAnnotationsRequest) GetDelete() []string {
	if x != nil {
		return x.Delete
	}
	return nil
}

type SetAnnotationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAnnotationsResponse) Reset() {
	*x = SetAnnotationsResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAnnotationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAnnotationsResponse) ProtoMessage() {}

func (x *SetAnnotationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAnnotationsResponse.ProtoReflect.Descriptor instead.
func (*SetAnnotationsResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{12}
}

type TrimRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Stream string                 `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	// before_id — all entries whose ID is less than or equal to this value
	// are deleted from the stream.
	BeforeId      string `protobuf:"bytes,2,opt,name=before_id,json=beforeId,proto3" json:"before_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrimRequest) Reset() {
	*x = TrimRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrimRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrimRequest) ProtoMessage() {}

func (x *TrimRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrimRequest.ProtoReflect.Descriptor instead.
func (*TrimRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{13}
}

func (x *TrimRequest) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *TrimRequest) GetBeforeId() string {
	if x != nil {
		return x.BeforeId
	}
	return ""
}

type TrimResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// deleted is the number of entries that were removed.
	Deleted       int64 `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrimResponse) Reset() {
	*x = TrimResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrimResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrimResponse) ProtoMessage() {}

func (x *TrimResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrimResponse.ProtoReflect.Descriptor instead.
func (*TrimResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{14}
}

func (x *TrimResponse) GetDeleted() int64 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

type ListStreamIDsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// after is the cursor: only stream IDs strictly greater than this value
	// are returned. Empty string means "from the beginning".
	After string `protobuf:"bytes,1,opt,name=after,proto3" json:"after,omitempty"`
	// limit caps the number of IDs returned. 0 means the backend default (100).
	Limit         int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStreamIDsRequest) Reset() {
	*x = ListStreamIDsRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStreamIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStreamIDsRequest) ProtoMessage() {}

func (x *ListStreamIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStreamIDsRequest.ProtoReflect.Descriptor instead.
func (*ListStreamIDsRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{15}
}

func (x *ListStreamIDsRequest) GetAfter() string {
	if x != nil {
		return x.After
	}
	return ""
}

func (x *ListStreamIDsRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListStreamIDsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// stream_ids is the ordered list of distinct stream IDs with at least one entry.
	StreamIds     []string `protobuf:"bytes,1,rep,name=stream_ids,json=streamIds,proto3" json:"stream_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStreamIDsResponse) Reset() {
	*x = ListStreamIDsResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStreamIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStreamIDsResponse) ProtoMessage() {}

func (x *ListStreamIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStreamIDsResponse.ProtoReflect.Descriptor instead.
func (*ListStreamIDsResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{16}
}

func (x *ListStreamIDsResponse) GetStreamIds() []string {
	if x != nil {
		return x.StreamIds
	}
	return nil
}

type RenameStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the current human-readable stream name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// new_name is the desired new name for the stream.
	NewName       string `protobuf:"bytes,2,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameStreamRequest) Reset() {
	*x = RenameStreamRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameStreamRequest) ProtoMessage() {}

func (x *RenameStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameStreamRequest.ProtoReflect.Descriptor instead.
func (*RenameStreamRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{17}
}

func (x *RenameStreamRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RenameStreamRequest) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

type RenameStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameStreamResponse) Reset() {
	*x = RenameStreamResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameStreamResponse) ProtoMessage() {}

func (x *RenameStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameStreamResponse.ProtoReflect.Descriptor instead.
func (*RenameStreamResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{18}
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{19}
}

type HealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status is "ok" when the backend is reachable, or an error description otherwise.
	Status        string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{20}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_ledger_v1_ledger_proto protoreflect.FileDescriptor

const file_ledger_v1_ledger_proto_rawDesc = "" +
	"\n" +
	"\x16ledger/v1/ledger.proto\x12\tledger.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x99\x02\n" +
	"\n" +
	"EntryInput\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12\x1b\n" +
	"\torder_key\x18\x02 \x01(\tR\borderKey\x12\x1b\n" +
	"\tdedup_key\x18\x03 \x01(\tR\bdedupKey\x12%\n" +
	"\x0eschema_version\x18\x04 \x01(\x03R\rschemaVersion\x12?\n" +
	"\bmetadata\x18\x05 \x03(\v2#.ledger.v1.EntryInput.MetadataEntryR\bmetadata\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb2\x04\n" +
	"\x05Entry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06stream\x18\x02 \x01(\tR\x06stream\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1b\n" +
	"\torder_key\x18\x04 \x01(\tR\borderKey\x12\x1b\n" +
	"\tdedup_key\x18\x05 \x01(\tR\bdedupKey\x12%\n" +
	"\x0eschema_version\x18\x06 \x01(\x03R\rschemaVersion\x12:\n" +
	"\bmetadata\x18\a \x03(\v2\x1e.ledger.v1.Entry.MetadataEntryR\bmetadata\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x12C\n" +
	"\vannotations\x18\t \x03(\v2!.ledger.v1.Entry.AnnotationsEntryR\vannotations\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x97\x01\n" +
	"\vReadOptions\x12\x14\n" +
	"\x05after\x18\x01 \x01(\tR\x05after\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x12\n" +
	"\x04desc\x18\x03 \x01(\bR\x04desc\x12\x1b\n" +
	"\torder_key\x18\x04 \x01(\tR\borderKey\x12\x10\n" +
	"\x03tag\x18\x05 \x01(\tR\x03tag\x12\x19\n" +
	"\ball_tags\x18\x06 \x03(\tR\aallTags\"X\n" +
	"\rAppendRequest\x12\x16\n" +
	"\x06stream\x18\x01 \x01(\tR\x06stream\x12/\n" +
	"\aentries\x18\x02 \x03(\v2\x15.ledger.v1.EntryInputR\aentries\"\"\n" +
	"\x0eAppendResponse\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"W\n" +
	"\vReadRequest\x12\x16\n" +
	"\x06stream\x18\x01 \x01(\tR\x06stream\x120\n" +
	"\aoptions\x18\x02 \x01(\v2\x16.ledger.v1.ReadOptionsR\aoptions\":\n" +
	"\fReadResponse\x12*\n" +
	"\aentries\x18\x01 \x03(\v2\x10.ledger.v1.EntryR\aentries\"&\n" +
	"\fCountRequest\x12\x16\n" +
	"\x06stream\x18\x01 \x01(\tR\x06stream\"%\n" +
	"\rCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"L\n" +
	"\x0eSetTagsRequest\x12\x16\n" +
	"\x06stream\x18\x01 \x01(\tR\x06stream\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\"\x11\n" +
	"\x0fSetTagsResponse\"\xcc\x01\n" +
	"\x15SetAnnotationsRequest\x12\x16\n" +
	"\x06stream\x18\x01 \x01(\tR\x06stream\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12;\n" +
	"\x03set\x18\x03 \x03(\v2).ledger.v1.SetAnnotationsRequest.SetEntryR\x03set\x12\x16\n" +
	"\x06delete\x18\x04 \x03(\tR\x06delete\x1a6\n" +
	"\bSetEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x18\n" +
	"\x16SetAnnotationsResponse\"B\n" +
	"\vTrimRequest\x12\x16\n" +
	"\x06stream\x18\x01 \x01(\tR\x06stream\x12\x1b\n" +
	"\tbefore_id\x18\x02 \x01(\tR\bbeforeId\"(\n" +
	"\fTrimResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\x03R\adeleted\"B\n" +
	"\x14ListStreamIDsRequest\x12\x14\n" +
	"\x05after\x18\x01 \x01(\tR\x05after\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\"6\n" +
	"\x15ListStreamIDsResponse\x12\x1d\n" +
	"\n" +
	"stream_ids\x18\x01 \x03(\tR\tstreamIds\"D\n" +
	"\x13RenameStreamRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bnew_name\x18\x02 \x01(\tR\anewName\"\x16\n" +
	"\x14RenameStreamResponse\"\x0f\n" +
	"\rHealthRequest\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xf9\x04\n" +
	"\rLedgerService\x12=\n" +
	"\x06Append\x12\x18.ledger.v1.AppendRequest\x1a\x19.ledger.v1.AppendResponse\x127\n" +
	"\x04Read\x12\x16.ledger.v1.ReadRequest\x1a\x17.ledger.v1.ReadResponse\x12:\n" +
	"\x05Count\x12\x17.ledger.v1.CountRequest\x1a\x18.ledger.v1.CountResponse\x12@\n" +
	"\aSetTags\x12\x19.ledger.v1.SetTagsRequest\x1a\x1a.ledger.v1.SetTagsResponse\x12U\n" +
	"\x0eSetAnnotations\x12 .ledger.v1.SetAnnotationsRequest\x1a!.ledger.v1.SetAnnotationsResponse\x127\n" +
	"\x04Trim\x12\x16.ledger.v1.TrimRequest\x1a\x17.ledger.v1.TrimResponse\x12R\n" +
	"\rListStreamIDs\x12\x1f.ledger.v1.ListStreamIDsRequest\x1a .ledger.v1.ListStreamIDsResponse\x12O\n" +
	"\fRenameStream\x12\x1e.ledger.v1.RenameStreamRequest\x1a\x1f.ledger.v1.RenameStreamResponse\x12=\n" +
	"\x06Health\x12\x18.ledger.v1.HealthRequest\x1a\x19.ledger.v1.HealthResponseB3Z1github.com/rbaliyan/ledger/api/ledger/v1;ledgerv1b\x06proto3"

var (
	file_ledger_v1_ledger_proto_rawDescOnce sync.Once
	file_ledger_v1_ledger_proto_rawDescData []byte
)

func file_ledger_v1_ledger_proto_rawDescGZIP() []byte {
	file_ledger_v1_ledger_proto_rawDescOnce.Do(func() {
		file_ledger_v1_ledger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ledger_v1_ledger_proto_rawDesc), len(file_ledger_v1_ledger_proto_rawDesc)))
	})
	return file_ledger_v1_ledger_proto_rawDescData
}

var file_ledger_v1_ledger_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_ledger_v1_ledger_proto_goTypes = []any{
	(*EntryInput)(nil),             // 0: ledger.v1.EntryInput
	(*Entry)(nil),                  // 1: ledger.v1.Entry
	(*ReadOptions)(nil),            // 2: ledger.v1.ReadOptions
	(*AppendRequest)(nil),          // 3: ledger.v1.AppendRequest
	(*AppendResponse)(nil),         // 4: ledger.v1.AppendResponse
	(*ReadRequest)(nil),            // 5: ledger.v1.ReadRequest
	(*ReadResponse)(nil),           // 6: ledger.v1.ReadResponse
	(*CountRequest)(nil),           // 7: ledger.v1.CountRequest
	(*CountResponse)(nil),          // 8: ledger.v1.CountResponse
	(*SetTagsRequest)(nil),         // 9: ledger.v1.SetTagsRequest
	(*SetTagsResponse)(nil),        // 10: ledger.v1.SetTagsResponse
	(*SetAnnotationsRequest)(nil),  // 11: ledger.v1.SetAnnotationsRequest
	(*SetAnnotationsResponse)(nil), // 12: ledger.v1.SetAnnotationsResponse
	(*TrimRequest)(nil),            // 13: ledger.v1.TrimRequest
	(*TrimResponse)(nil),           // 14: ledger.v1.TrimResponse
	(*ListStreamIDsRequest)(nil),   // 15: ledger.v1.ListStreamIDsRequest
	(*ListStreamIDsResponse)(nil),  // 16: ledger.v1.ListStreamIDsResponse
	(*RenameStreamRequest)(nil),    // 17: ledger.v1.RenameStreamRequest
	(*RenameStreamResponse)(nil),   // 18: ledger.v1.RenameStreamResponse
	(*HealthRequest)(nil),          // 19: ledger.v1.HealthRequest
	(*HealthResponse)(nil),         // 20: ledger.v1.HealthResponse
	nil,                            // 21: ledger.v1.EntryInput.MetadataEntry
	nil,                            // 22: ledger.v1.Entry.MetadataEntry
	nil,                            // 23: ledger.v1.Entry.AnnotationsEntry
	nil,                            // 24: ledger.v1.SetAnnotationsRequest.SetEntry
	(*timestamppb.Timestamp)(nil),  // 25: google.protobuf.Timestamp
}
var file_ledger_v1_ledger_proto_depIdxs = []int32{
	21, // 0: ledger.v1.EntryInput.metadata:type_name -> ledger.v1.EntryInput.MetadataEntry
	22, // 1: ledger.v1.Entry.metadata:type_name -> ledger.v1.Entry.MetadataEntry
	23, // 2: ledger.v1.Entry.annotations:type_name -> ledger.v1.Entry.AnnotationsEntry
	25, // 3: ledger.v1.Entry.created_at:type_name -> google.protobuf.Timestamp
	25, // 4: ledger.v1.Entry.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 5: ledger.v1.AppendRequest.entries:type_name -> ledger.v1.EntryInput
	2,  // 6: ledger.v1.ReadRequest.options:type_name -> ledger.v1.ReadOptions
	1,  // 7: ledger.v1.ReadResponse.entries:type_name -> ledger.v1.Entry
	24, // 8: ledger.v1.SetAnnotationsRequest.set:type_name -> ledger.v1.SetAnnotationsRequest.SetEntry
	3,  // 9: ledger.v1.LedgerService.Append:input_type -> ledger.v1.AppendRequest
	5,  // 10: ledger.v1.LedgerService.Read:input_type -> ledger.v1.ReadRequest
	7,  // 11: ledger.v1.LedgerService.Count:input_type -> ledger.v1.CountRequest
	9,  // 12: ledger.v1.LedgerService.SetTags:input_type -> ledger.v1.SetTagsRequest
	11, // 13: ledger.v1.LedgerService.SetAnnotations:input_type -> ledger.v1.SetAnnotationsRequest
	13, // 14: ledger.v1.LedgerService.Trim:input_type -> ledger.v1.TrimRequest
	15, // 15: ledger.v1.LedgerService.ListStreamIDs:input_type -> ledger.v1.ListStreamIDsRequest
	17, // 16: ledger.v1.LedgerService.RenameStream:input_type -> ledger.v1.RenameStreamRequest
	19, // 17: ledger.v1.LedgerService.Health:input_type -> ledger.v1.HealthRequest
	4,  // 18: ledger.v1.LedgerService.Append:output_type -> ledger.v1.AppendResponse
	6,  // 19: ledger.v1.LedgerService.Read:output_type -> ledger.v1.ReadResponse
	8,  // 20: ledger.v1.LedgerService.Count:output_type -> ledger.v1.CountResponse
	10, // 21: ledger.v1.LedgerService.SetTags:output_type -> ledger.v1.SetTagsResponse
	12, // 22: ledger.v1.LedgerService.SetAnnotations:output_type -> ledger.v1.SetAnnotationsResponse
	14, // 23: ledger.v1.LedgerService.Trim:output_type -> ledger.v1.TrimResponse
	16, // 24: ledger.v1.LedgerService.ListStreamIDs:output_type -> ledger.v1.ListStreamIDsResponse
	18, // 25: ledger.v1.LedgerService.RenameStream:output_type -> ledger.v1.RenameStreamResponse
	20, // 26: ledger.v1.LedgerService.Health:output_type -> ledger.v1.HealthResponse
	18, // [18:27] is the sub-list for method output_type
	9,  // [9:18] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_ledger_v1_ledger_proto_init() }
func file_ledger_v1_ledger_proto_init() {
	if File_ledger_v1_ledger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ledger_v1_ledger_proto_rawDesc), len(file_ledger_v1_ledger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ledger_v1_ledger_proto_goTypes,
		DependencyIndexes: file_ledger_v1_ledger_proto_depIdxs,
		MessageInfos:      file_ledger_v1_ledger_proto_msgTypes,
	}.Build()
	File_ledger_v1_ledger_proto = out.File
	file_ledger_v1_ledger_proto_goTypes = nil
	file_ledger_v1_ledger_proto_depIdxs = nil
}
